spring:
  data:
    redis:
      url: ${REDIS_URI}

server:
  port: 8083


gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/